export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_END = "AUTH_END";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const SELL_START = "SELL_START";
export const TRANSFER_LIST = "TRANSFER_LIST";
export const DESCRIPTION = "DESCRIPTION";
export const PRICE = "PRICE";
export const SELL_END_WAIT = "SELL_END_WAIT";
export const SELL_END="SELL_END";
export const IMAGE_UPLOAD = "IMAGE_UPLOAD";
// export const PHALTU = "PHALTU"

export const GET_SELLERS_START = "GET_SELLERS_START";
export const GET_SELLERS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_FAIL = "GET_SELLERS_FAIL";

export const GET_SELLERS__DETAILS_START = "GET_SELLERS_START";
export const GET_SELLERS_DETAILS_SUCCESS = "GET_SELLERS_SUCCESS";
export const GET_SELLERS_DETAILS_FAIL = "GET_SELLERS_FAIL";
